### ISSUE TITLE
Add another upload a file field when "Career options" is selected

### ISSUE THREAD

**Issue by noamhoze** [Vayyar/vayyar-wp#12]
For that issue we need to make sure that the wufoo form also had an upload file field.
We also need to verify that this is an either pdf or word document.

**Comment by noamhoze** [comment]
@migkapa, please don't implement anything in the live site before consulting me.

**Comment by ygord-vayyar** [comment]
After input from @noamhoze and HR, this has changed - task is now to remove the career option from the dropdown.
