### ISSUE TITLE
Configure a staging site for Vayyar

### ISSUE THREAD

**Issue by noamhoze** [Vayyar/vayyar-wp#13]

**Comment by migkapa** [comment]
Please create a staging.vayyar.com subdomain 
pointing to a "staging" folder inside vayyar.com's public_html.

We wont need another cpanel just for that, but keep it there in different folder.

**Comment by noamhoze** [comment]
That's OK.
Please do that and let me know when it's done so we can add the DNS record.

**Comment by migkapa** [comment]
hi @noamhoze 
I was able to add the subdomain from the cpanel. 
You can find the stage under staging.vayyar.com 

Protection credentials are the same as walabot

**Comment by noamhoze** [comment]
Great, thanks!
