### ISSUE TITLE
Home page: "As seen on" - formatting

### ISSUE THREAD

**Issue by ygord-vayyar** [Vayyar/vayyar-wp#2]
![main_page_1](https://user-images.githubusercontent.com/35445812/35194268-57cf1b76-feb9-11e7-8269-57e77ef0594f.PNG)

Fix formatting to match old site

**Comment by migkapa** [comment]
Added a row class to that section rows and added it as a global section

<img width="939" alt="as_soon" src="https://user-images.githubusercontent.com/2510443/35197088-1d964bec-fedb-11e7-8d22-400319231b62.png">
