### ISSUE TITLE
Tech page: fix styling

### ISSUE THREAD

**Issue by ygord-vayyar** [Vayyar/vayyar-wp#3]
![tech_page_1](https://user-images.githubusercontent.com/35445812/35194273-8b523a46-feb9-11e7-9c8e-940c122172e6.PNG)
Fix line spacing

![tech_page_2](https://user-images.githubusercontent.com/35445812/35194280-abddb06a-feb9-11e7-94df-f9eeb801d28a.PNG)
Make text font smaller

**Comment by migkapa** [comment]
Fixed line height 
https://github.com/Vayyar/vayyar-wp/commit/023cdfba45d21ee97d2e7f599460e0f255e738db
