### ISSUE TITLE
Header: 'Smart Office' title not shown after jump

### ISSUE THREAD

**Issue by ygord-vayyar** [Vayyar/vayyar-wp#7]
When clicking "Smart Office", eg. in the header, the section title of "Smart Office" is obscured by the floating header, and cannot be seen. (It does work once you're on the page itself, though) Also the gap between the title and the content is too big (may be related).

![smart_office_header_missing](https://user-images.githubusercontent.com/35445812/35194376-709a69d8-febb-11e7-9f2c-4dc6e9ac1fbd.PNG)

**Comment by migkapa** [comment]
Added an empty row with the office id above the title and made the space smaller
